### ISSUE TITLE
Expose pages through API in addition to iFrame option

### ISSUE THREAD

**Issue by MeStrak** [Sanofi-IADC/konviw#281]
**Is your feature request related to a problem? Please describe.**
Today the only way to embed a page from Konviw is via iFrame. This does work well but comes with the limitations of an iFrame. For example occasional resizing issues, JS errors not detected within the embedding app by our APM tool.

It would be possible to achieve better integration if the content was available via API like a headless CMS, so it could be fetched and rendered as required by the embedding app.

**Describe the solution you'd like**
- Add an additional endpoint returning the page body, and other properties (title, read time, ...) in the JSON response
- This would move Konviw more in the direction of a simple headless CMS proxy in front of Confluence, with the advantage that iFrame can still be used for fast embedding
- Embedding app would need to load supporting .js and .css files, but this could possibly be improved in the future to provide a helper.js to add the imports and to apply syntax highlighting server-side
- Rename existing internal function getHtmlBody() to getHtmlDocument() as it returns the full page HTML, not only the body

**Describe alternatives you've considered**
- New API endpoint as described above
- Host as a micro app using https://single-spa.js.org/ (not chosen as it's more complex to implement and embed)

**Additional context**
This implementation would be very similar to the Articles endpoint on the Dev.to API: https://developers.forem.com/api#operation/getArticleByPath. It returns a JSON response containing the page HTML body (not the full document as rendered in Konviw), along with several other page properties. There's a good example of how it can be used in this article: https://nuxtjs.org/tutorials/build-dev-to-clone-with-nuxt-new-fetch.

**Comment by MeStrak** [comment]
Created a branch to start working on this (the main change is really simple): https://github.com/Sanofi-IADC/konviw/tree/feat/page-as-api-call.

With a jsfiddle for testing it: https://jsfiddle.net/w01dnyc6/24/

Page can be embedded with:

```html
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="http://localhost:3000/cpv/css/custom.css?cache=1.22.4">
    <link rel="stylesheet" href="http://localhost:3000/cpv/css/all.min.css?cache=1.22.4">
    <link rel="stylesheet" href="http://localhost:3000/cpv/highlight/zenburn.min.css?cache=1.22.4">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.3.1/highlight.min.js" integrity="sha512-Pbb8o120v5/hN/a6LjF4N4Lxou+xYZ0QcVF8J6TWhBbHmctQWd8O6xTDmHpE/91OjPzCk4JRoiJsexHYg4SotQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script>
		</script>
  </head>
  <body>
    Some content
    <div id=konviwcontent>
    </div>
  </body>
</html>
```

```js
(() => {
  fetch("http://localhost:3000/cpv/wiki/api/spaces/konviw/pages/98535")
    .then((response) => {
      response.json().then((data) => {
        document.getElementById("konviwcontent").innerHTML = data.html_body;
        hljs.highlightAll();
      });
    })
    .catch((error) => {
      console.log(error);
    });
})();
```

And page renders:
![image](https://user-images.githubusercontent.com/31989238/146928531-c43cd658-0ad0-4b92-8be0-82953f855829.png)

The main drawback at the moment is that it's trickier to get all features working correctly (zooming, etc.). Checking to see if I can find a simple way of doing that, or if it's better just to clearly document it.

**Comment by PiiXiieeS** [comment]
Hi @MeStrak !
Many interesting points raising up from this idea.

- [x] First the API endpoint should be part of the module `proxy-api` and not `proxy-page` because this last one is serving HTML responses and `proxy-api` serves RestAPI JSON.

- [ ] The **most dangerous** change is see in your proposal is the move from relative path to absolute path to properly resolve all the assets: `const webBasePath = config.get('web.basePath')` to `const webBasePath = config.get('web.absoluteBasePath')`.
This could introduce a regression we have to test thoroughly.
BTW, here we did a change a few weeks ago in the configuration and 
`process.env.CPV_BASEPATH` now includes the port, example `localhost:3000`; so you just have to change your configuration. (I probably have to update this configuration change in the project documentation).
In previous API end points where I had to resolve absolute URLs, I did concatenate `${baseHost}${basePath}` like here
https://github.com/Sanofi-IADC/konviw/blob/9f295b2d985c395ecdb4c68f7481f2d24bcfe106/src/proxy-api/proxy-api.service.ts#L268
while having a `absoluteBasePath` in [configuration.ts](https://github.com/Sanofi-IADC/konviw/blob/21d3893b8d01cc50f474d186a95b677a11cdb986/src/config/configuration.ts#L12) looks much better.

- [x] What steps to apply is also a question to address with this dedicated API endpoint. As we did already with renderPage or renderSlides we just have to select the appropriate steps according to the expected outcome. So in my opinion it is fine that zooming is not working, because we should skip this step and handle the zooming via the vue page (as the aim of the API is to be headless).
So for zooming we just have to add
`<script src="https://unpkg.com/zooming@2.1.1/build/zooming.min.js"></script>`
and this command to the HTML page:
`new Zooming({}).listen('.confluence-embedded-image')`
See the fix in this jsfiddle: https://jsfiddle.net/piixiiees/pkgmhL7r/

- [ ] This is my first feeling on the steps we shall keep and remove for an API headless BODY endpoint
  - [NO] fixHtmlHead(this.config)(this.context);
  - [NO] fixContentWidth()(this.context);
  - [NO] addMessageBus(this.config)(this.context);
  - [NO] addZooming(this.config)(this.context);  
  - [NO] addNoZoom()(this.context);
  - [NO] addCustomCss(this.config, style)(this.context);
  - [NO] addHeaderBlog()(this.context);
  - [NO] addHeaderTitle()(this.context);
  - [NO] addTheme()(this.context);
  - [NO] addScrollToTop()(this.context);    // even if this works I would handle this in the parent page
  - [NO] addReadingProgressBar()(this.context);
  - [NO] addWebStatsTracker(this.config)(this.context);
  - [YES] fixLinks(this.config)(this.context);
  - [YES] fixToc()(this.context);
  - [YES] fixEmojis(this.config)(this.context);
  - [YES] fixDrawioMacro(this.config)(this.context);
  - [YES] fixChartMacro(this.config)(this.context);
  - [YES] fixExpander()(this.context);
  - [YES] fixUserProfile()(this.context);
  - [YES] fixVideo()(this.context);
  - [YES] fixTableColGroup()(this.context);
  - [YES] fixEmptyLineIncludePage()(this.context);
  - [YES] fixRoadmap(this.config)(this.context);
  - [YES] fixFrameAllowFullscreen()(this.context);
  - [YES] addHighlightjs(this.config)(this.context);    // Activation needed in the parent page
  - [YES] addCopyLinks()(this.context);
  - [YES] await addJiraPromise;
  - [YES] delUnnecessaryCode()(this.context);

**Comment by PiiXiieeS** [comment]
One more point that triggers my attention while reviewing your code.
Currently we are using the API endpoint from Confluence:
`/wiki/rest/api/content/${pageId}`
https://developer.atlassian.com/cloud/confluence/rest/api-group-content/#api-wiki-rest-api-content-id-get
expanding the body as `body.styled_view`, which retrieves the full `html`.
We could simple shift to `body.view`, which resolves just the inner body without the html `head` or `body` tags.

It could improve the performance as the Confluence API payload shall be much smaller without inline CSS in the header. I just have to make some tests to make sure we don't miss anything.

I create a dedicated issue for this: https://github.com/Sanofi-IADC/konviw/issues/285

**Comment by MeStrak** [comment]
Thanks for all the feedback @PiiXiieeS!

> First the API endpoint should be part of the module proxy-api and not proxy-page because this last one is serving HTML responses and proxy-api serves RestAPI JSON.

Yes, good point - I will move it. I debated it a bit at first and in the end to cut my procrastination short I went with the page service for testing as it's so closely related to the other page functionality.

> The most dangerous change is see in your proposal is the move from relative path to absolute path to properly resolve all the assets: const webBasePath = config.get('web.basePath') to const webBasePath = config.get('web.absoluteBasePath').

Definitely - this is the only part so far that touches another part of the app. It is necessary because the page is unlikely to be hosted on the same server with this new model. I have done some light testing so far but definitely somewhere to check in more detail.

> This is my first feeling on the steps we shall keep and remove for an API headless BODY endpoint ...
I think I was pretty much aligned with this on my first review of them too. A couple of things:
- addMessageBus: is it still relevant in this case? I wonder if it's more for the parent application to manage this as they would any other API driven content without the need for the messaging part. Thinking about using in NuxtJS this would allow the parent app to know about navigation within pages: https://medium.com/@wearethreebears/handle-api-driven-content-links-in-nuxt-js-fe2e31ecbeeb. I'm not sure about other frameworks though.
- For highlight.js the other thought I had was to possibly do all formatting on the server side and avoid the need for referenced dependencies today. For example with this: https://github.com/rehypejs/rehype-highlight (rehype could also be an interesting model to look at generally for the type of processing that we do)
- I need to double check whether injecting CSS links into innerHtml works or if we have the same issue as with javascript where it has to be added by the embedding page (otherwise it is seen as text only). It's an easy workaround anyway if needed as we can just have a single .css file which is referenced by the embedding page which links to the relevant version of other .css files.

> We could simple shift to body.view, which resolves just the inner body without the html head or body tags.

Good suggestion - I didn't know about this so just stripped the head and body tags out from the current HTML but if the content between the body still has the same tags applied then this definitely makes sense. Let me know if I can help with the testing.

**Comment by PiiXiieeS** [comment]
My bad, you are fully right `addMessageBus` is not needed for the embedded approach.
We may have to put a name to this API new processing to well differentiate in the documentation from embedded iFrames.
What about _konviw embedded app_?

Great idea about highlight.js and make all the format heavy lifting in the server and just inject the CSS from the hosting app.
Bundling all the CSS in a single file might be the true challenge, taking into account those come all from different sources. We may lose on maintainability. See may intention in https://github.com/Sanofi-IADC/konviw/issues/284 to go on bundling with individual packaging via webpack.

Inlining CSS within the HTML will make the solution very isolated, but will increase substantially the payload and performance as styles will be shipped for every single request (I do not think they will be cached that way). Overall in terms of performance, I would rather keep CSS to be defined by the parent app. Which also makes sense to delegate the final styling to the parent App.

I implemented the move to `body.view` in the pull request https://github.com/Sanofi-IADC/konviw/pull/287
All in all quite straight forward, while the side effect on the missing `<div id="Content">` forced me to adjust many testing cases. @MeStrak let me know if you can have a look and test on your side.

**Comment by MeStrak** [comment]
> I implemented the move to `body.view` in the pull request #287
> All in all quite straight forward, while the side effect on the missing `<div id="Content">` forced me to adjust many testing cases. @MeStrak let me know if you can have a look and test on your side.

Looks really good and worked (almost) first time for me. I proposed a few simple changes in the PR as currently it's still wrapping the result in `<html>` tags which will mean I can totally remove `getHtmlnnerBody( ... )` from this implementation.

**Comment by MeStrak** [comment]
> We may have to put a name to this API new processing to well differentiate in the documentation from embedded iFrames.
> What about _konviw embedded app_?

@PiiXiieeS yes you're right - we need a good way to distinguish them. Although I was saying 'embedding page' before, perhaps it is more accurate to say that the iFrame is a case where the page embedded, and the new API option is more 'integration' as it allows more advanced integration with other features on your website. What about something like the following?

**Pre-rendered pages**
_Use pre-rendered. served pages with Konviw as a standalone server, or for quick and easy embedding in your site_
A rendered page hosted from the Konviw server. This option allows the user to display a read only version of a Confluence page directly in their browser, or a developer to quickly embed content into a page using an iFrame. Includes some cool features to ease use including zooming, hovering table of contents and a read only page link generator.

**Headless pages API**
_Treat Confluence as a headless CMS to eamlessly integrate Confluence content with your website or app_
Download page data through a headless CMS endpoint for integration directly in an application page content into your app. This is a more advanced option enabling transparent integration into your website or app.

___

Another pedantic thought after reading what I wrote above ...
I wonder if we can truly call this a headless CMS as we still include page styling such as width, columns, etc. Do you think that something like _hybrid CMS_, or _styled headless CMS_ could be more accurate, or is it too confusing to add more terms like this?

**Comment by MeStrak** [comment]
@PiiXiieeS @kiru42 I did a few more updates to this and merged with the latest released versions. I marked the new endpoint as an alpha version only as there are some outstanding issues but the basic functionality is working and doesn't impact the rest of the app.

https://github.com/Sanofi-IADC/konviw/pull/286 is ready to review when you have time 😺
